### PR TITLE
Fixes #240

### LINKED ISSUE #240: Players rating doesn't work.

### PR DESCRIPTION
**Pull request by norraxx**

### CODE REVIEW

**Comment by norraxx** [comment]
@Brutus5000 I've fixed postgresql like temporary table syntax to MySQL one.

File: migrations/V99__player_rating_unique_key_fix.sql [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+SELECT r1.id
+FROM leaderboard_rating AS r1
+         INNER JOIN leaderboard_rating AS r2 ON
+        r1.id != r2.id AND
+        r1.login_id = r2.login_id AND
+        r1.leaderboard_id = r2.leaderboard_id AND
+        r1.create_time > r2.create_time;
+
+DELETE FROM leaderboard_rating lr
+INNER JOIN duplicates d onlr.id = d.id;
```
Comment (norraxx) [inline migrations/V99__player_rating_unique_key_fix.sql]: `on ` - space needed after `on`

**Comment by Brutus5000** [comment]
I removed the actual cleanup as this causes Travis timeouts and only needs to run on production once.
